services:
  - type: web
    name: agricontract
    runtime: python
    plan: free

    buildCommand: ./build.sh

    startCommand: python -m gunicorn agricontract_project.wsgi:application

    envVars:
      - key: SECRET_KEY
        generateValue: true

      - key: DEBUG
        value: "False"

      - key: DATABASE_URL
        fromDatabase:
          name: agricontract-db
          property: connectionString

      - key: PYTHON_VERSION
        value: 3.11.9

databases:
  - name: agricontract-db
    plan: free