services:
  - type: web
    name: agricontract
    runtime: python
    plan: free

    buildCommand: bash build.sh

    startCommand: python -m gunicorn agricontract_project.wsgi:application

    envVars:
      - key: SECRET_KEY
        generateValue: true

      - key: DEBUG
        value: "False"

      - key: PYTHON_VERSION
        value: "3.11.9"